name: CI/CD Pipeline for React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker
        uses: docker/setup-qemu-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-react-app .

      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 my-react-app

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy the app to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          CI: true
